# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from api import metrics_pb2 as api_dot_metrics__pb2


class MetricsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Query = channel.unary_unary(
        '/api.Metrics/Query',
        request_serializer=api_dot_metrics__pb2.QueryMetricsRequest.SerializeToString,
        response_deserializer=api_dot_metrics__pb2.QueryMetricsResponse.FromString,
        )


class MetricsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetricsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=api_dot_metrics__pb2.QueryMetricsRequest.FromString,
          response_serializer=api_dot_metrics__pb2.QueryMetricsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.Metrics', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
